apiVersion: v1
kind: ReplicationController
metadata:
  name: myonlineapp-rc
spec:
  replicas: 4
  selector:
      app: myonlineapp
  template:
    metadata: 
      labels:
          app: myonlineapp
    spec:
      containers:
        - name: myonlineapp-container
          image: nginx
          ports:
            - containerPort: 80