apiVersion: v1
kind: ReplicationController
metadata:
  name: myjenkins-rc
spec:
  replicas: 4
  selector:
      app: myjenkins
      versions: 2.6.2
  template:
    metadata: 
      labels:
          app: myjenkins
          versions: 2.6.2
    spec:
      containers:
        - name: myjenkins-container
          image: dockers87/myjenkinsimage
          ports:
            - containerPort: 8080