apiVersion: v1
kind: Service
metadata:
  name: mynginx-svc
  labels:
    app: myonlineapp
spec:
  type: NodePort
  ports:
  - port: 8080
    nodeport: 30001
    protocol: TCP
  selector:
      app: myonlinestore
